### ISSUE TITLE
Small suggestions

### ISSUE THREAD

**Issue by biermanncarl** [SlithyMatt/cbm-wordslide#1]
Found obscure words "aisle", "aleph" which I've never heard before.
Didn't include "flint", "plank", which seemed like common knowledge to me.

I typed in "ERROR", and only one of the R letters got highlighted yellow. I wasn't sure whether only that one or all of them were in the wrong position (curiously, not the first one, but the third one got highlighted). The alternative would be to highlight all R letters, but that could imply that the hidden word contains three times R. Don't know what is better. In any case, I would highlight the first occurrence of a letter.

About colors: highlighted letters are sometimes hard to read, since they are black on black background, and the highlight color doesn't always go around the entire letter. The solution would be to choose a different foreground color for highlighted letters, maybe dark grey? Red would have good contrast to green and yellow, but would falsely imply that something is wrong. Blue would have worse contrast, and would also look ugly imo. Hard times...
Another approach would be to overlay characters (screen codes 100 and/or 101) to adjacent positions to create an extra row of pixels in the background color and thus complete the border. This would only be doable using the two tile layers of VERA I think.

**Comment by SlithyMatt** [comment]
Aisle is a very common word, it's the space you walk between sections of seats in a theatre or plane. Aleph is a a bit obscure, so I'll delete that, and add flint and plank.

Only highlighting one of the characters when only one exists in the word is part of the game. That way, if there are at least two in the word, you will know if both are highlighted. Unfortunately, the highlighting is a limitation of PETSCII on the legacy Commodore machines. I will have more graphically sophisticated versions for later versions of the game that will break the code compatibility that we currently have.
